language: python
services:
- docker
git:
  depth: false
script:
- make test
deploy:
  provider: script
  script: make push
  on:
    branch: master
env:
  global:
  - secure: CgdAJM3ak20JAhRE1x83wNjsLZHat3LPgh8Mw8xLgckUDtZvduPHwWHFsXqwqMZeiMXSNEMCaV+tPIXxAseB0MnYQNnYz+ZCXv8LMvkb1nkWQHRFfN3Zghfwq0hckgbfFtFi7jyHlSfBRt+6pVOI1fk4hOu2SXmcxx1HpUu8byjy1Jk7fSo64pNff7SnR0b9REzpaRrG8qcg2uN8hZTtGUwfPuwxliOORWfvRy/z3Iz0uFqHV0TDUMYZdLpO8oMAS+jEizJjOzkjQw3Ek4fYhw4ifgbSBEbe8090kn+Il7mTATDun0qlZqlF1VzsXUzKz+QrxxKa+Ro1Izown2+MVab+B+G40x65WlPsEECD8Sq/UFrfo0qXp+xIx8CHJBPCDXHck29UwkzrQ8qMRcVobCdI12kZs7eJmnYUrWBTayXoQVi6WgiVy+/NcW8HQjNPy+pJHa/YWxurrR0iblEdGL7rJFnQt8XGMwOKfQVr5IQCYvXYnZOzrEhuzXbKCOTMdhI93L4UKX8wZ8nPRC1+F8DoxOwyguC69O+zMrMPBZ8RVpbihceZikr85HwNAy2YAw8rqm3LCpL7otv5AS8ET/U392GL3SQDy3Yu5aMmSgmxUhdRm1WJjpl5BenQKzrjY8AHjhMZPOGyUcTvHegn/AEwXkQIawejY+AoqRPGrUI=
  - secure: gfF3GTYkbcmKF1c3e3OtLry3x6OdhhWPvI6Woo3wCbL8C8+iSaQ2t2Zo0QbNZ4nj12Cpt1uXTGf7oIZ1WEvxKeLVLZG42fFUKmTlsF1hLLOk3mqJ3Rx7LeiRl3pwm/KPeQSL05XKgH3GT4R5rh20msVcSLukK26bp8hiAps+RkGHtJSsM3hx4upNbrLTibKb9sWzCQtw8vaQ9lU//ETucEASZKEbxdtCzDC+gUcqHIih5HaDjDD58cY/k+JIkveDscj52fmiLhdguKltADjY9qlBl7oFJogRDHCSvV1WVDBeK2ZVR9uGbpKvDPFFlmfdXzlKRtTDyISQyrGuVqHs9PP8cLTBvqdOlNxpuMFPa8XnJbPunVLzDqrnmiPzF8NncPNkeTGpAaoe19otVFzvhAsfv3ncQiIwNVTqYxNQI6BGDvdYehpa1zoJ46ALBESLG2YPEJX2Bdx98S+6LZCo8yt8HnhPaLhQXUAeNghM664hVfrb0Be9bir/NHKT66/dWYJ/RQikqmeI7Ay5McIz0C5nG6EXQ2vUE5KVu+PtSq0l58N1WsfFWpk9p545NsiQt3w6PXDJufd+DQ3/Tr4ROEZswzKME5bjCjMnCuzavUer0g7BPRSZG3z/8rJscuvFbZlMeQ0usXthwiwmcr0ayK5TrBQ5BrLgzwcuBvgPd/g=
